//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitter.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitter.App.Resources.Texts.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AddTeam_Button {
            get {
                return ResourceManager.GetString("AddTeam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own Team with administrator benefits!.
        /// </summary>
        public static string AddTeam_Text {
            get {
                return ResourceManager.GetString("AddTeam_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AddTeam_Title {
            get {
                return ResourceManager.GetString("AddTeam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser_Button {
            get {
                return ResourceManager.GetString("AddUser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another User and let him enjoy Fitter too!.
        /// </summary>
        public static string AddUser_Text {
            get {
                return ResourceManager.GetString("AddUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser_Title {
            get {
                return ResourceManager.GetString("AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin:.
        /// </summary>
        public static string Admin_Text {
            get {
                return ResourceManager.GetString("Admin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the author can delete the comment!.
        /// </summary>
        public static string CanNotDeleteComment_Message {
            get {
                return ResourceManager.GetString("CanNotDeleteComment_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the author can delete the post!.
        /// </summary>
        public static string CanNotDeletePost_Message {
            get {
                return ResourceManager.GetString("CanNotDeletePost_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the Admin can delete the team!.
        /// </summary>
        public static string CanNotDeleteTeam_Message {
            get {
                return ResourceManager.GetString("CanNotDeleteTeam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLang_Text {
            get {
                return ResourceManager.GetString("ChangeLang_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment_Button {
            get {
                return ResourceManager.GetString("Comment_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Post.
        /// </summary>
        public static string CreatePost_Button {
            get {
                return ResourceManager.GetString("CreatePost_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        public static string CreateTeam_Button {
            get {
                return ResourceManager.GetString("CreateTeam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser_Button {
            get {
                return ResourceManager.GetString("CreateUser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the comment?.
        /// </summary>
        public static string DeleteComment_Message {
            get {
                return ResourceManager.GetString("DeleteComment_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        public static string DeleteComment_MTitle {
            get {
                return ResourceManager.GetString("DeleteComment_MTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the post?.
        /// </summary>
        public static string DeletePost_Message {
            get {
                return ResourceManager.GetString("DeletePost_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Post.
        /// </summary>
        public static string DeletePost_MTitle {
            get {
                return ResourceManager.GetString("DeletePost_MTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the team?.
        /// </summary>
        public static string DeleteTeam_Message {
            get {
                return ResourceManager.GetString("DeleteTeam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Team.
        /// </summary>
        public static string DeleteTeam_MTitle {
            get {
                return ResourceManager.GetString("DeleteTeam_MTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstName_Text {
            get {
                return ResourceManager.GetString("FirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string FullName_Text {
            get {
                return ResourceManager.GetString("FullName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not kick the Admin!.
        /// </summary>
        public static string KickAdmin_Message {
            get {
                return ResourceManager.GetString("KickAdmin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity:.
        /// </summary>
        public static string LastActivity_Text {
            get {
                return ResourceManager.GetString("LastActivity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string LastName_Text {
            get {
                return ResourceManager.GetString("LastName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the Admin, you can not leave!.
        /// </summary>
        public static string LeaveAdmin_Message {
            get {
                return ResourceManager.GetString("LeaveAdmin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave the team?.
        /// </summary>
        public static string LeaveTeam_Message {
            get {
                return ResourceManager.GetString("LeaveTeam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Team.
        /// </summary>
        public static string LeaveTeam_MTitle {
            get {
                return ResourceManager.GetString("LeaveTeam_MTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string LoginError_Message {
            get {
                return ResourceManager.GetString("LoginError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Text.
        /// </summary>
        public static string MissingText_Message {
            get {
                return ResourceManager.GetString("MissingText_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists!.
        /// </summary>
        public static string NoUser_Message {
            get {
                return ResourceManager.GetString("NoUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLogin {
            get {
                return ResourceManager.GetString("PasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write what&apos;s on your mind....
        /// </summary>
        public static string Post_Message {
            get {
                return ResourceManager.GetString("Post_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title here....
        /// </summary>
        public static string PostTitle_Message {
            get {
                return ResourceManager.GetString("PostTitle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        public static string RemoveUser_Title {
            get {
                return ResourceManager.GetString("RemoveUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to apply changes..
        /// </summary>
        public static string Restart_Message {
            get {
                return ResourceManager.GetString("Restart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with typed name already exists!.
        /// </summary>
        public static string SameTeam_Message {
            get {
                return ResourceManager.GetString("SameTeam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with that email address already exists!.
        /// </summary>
        public static string SameUser_Message {
            get {
                return ResourceManager.GetString("SameUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string TeamDesc_Text {
            get {
                return ResourceManager.GetString("TeamDesc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team informations:.
        /// </summary>
        public static string TeamInfo_Title {
            get {
                return ResourceManager.GetString("TeamInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name:.
        /// </summary>
        public static string TeamName_Text {
            get {
                return ResourceManager.GetString("TeamName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsHeader_AppPanel {
            get {
                return ResourceManager.GetString("TeamsHeader_AppPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams:.
        /// </summary>
        public static string TeamsHeader_Text {
            get {
                return ResourceManager.GetString("TeamsHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information:.
        /// </summary>
        public static string UserInfo_Title {
            get {
                return ResourceManager.GetString("UserInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users in team:.
        /// </summary>
        public static string UsersInTeam_Text {
            get {
                return ResourceManager.GetString("UsersInTeam_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s teams:.
        /// </summary>
        public static string UsersTeams_Text {
            get {
                return ResourceManager.GetString("UsersTeams_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password!.
        /// </summary>
        public static string WrongPassword_Message {
            get {
                return ResourceManager.GetString("WrongPassword_Message", resourceCulture);
            }
        }
    }
}
