//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitter.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitter.App.Resources.Texts.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AddTeam_Button {
            get {
                return ResourceManager.GetString("AddTeam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own Team with administrator benefits!.
        /// </summary>
        public static string AddTeam_Text {
            get {
                return ResourceManager.GetString("AddTeam_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AddTeam_Title {
            get {
                return ResourceManager.GetString("AddTeam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser_Button {
            get {
                return ResourceManager.GetString("AddUser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another User and let him enjoy Fitter too!.
        /// </summary>
        public static string AddUser_Text {
            get {
                return ResourceManager.GetString("AddUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser_Title {
            get {
                return ResourceManager.GetString("AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin:.
        /// </summary>
        public static string Admin_Text {
            get {
                return ResourceManager.GetString("Admin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment_Button {
            get {
                return ResourceManager.GetString("Comment_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Post.
        /// </summary>
        public static string CreatePost_Button {
            get {
                return ResourceManager.GetString("CreatePost_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        public static string CreateTeam_Button {
            get {
                return ResourceManager.GetString("CreateTeam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser_Button {
            get {
                return ResourceManager.GetString("CreateUser_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstName_Text {
            get {
                return ResourceManager.GetString("FirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity:.
        /// </summary>
        public static string LastActivity_Text {
            get {
                return ResourceManager.GetString("LastActivity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string LastName_Text {
            get {
                return ResourceManager.GetString("LastName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string LoginError_Message {
            get {
                return ResourceManager.GetString("LoginError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLogin {
            get {
                return ResourceManager.GetString("PasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        public static string RemoveUser_Title {
            get {
                return ResourceManager.GetString("RemoveUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string TeamDesc_Text {
            get {
                return ResourceManager.GetString("TeamDesc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details:.
        /// </summary>
        public static string TeamDetails_DetailsTitle {
            get {
                return ResourceManager.GetString("TeamDetails_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamDetails_TeamTitle {
            get {
                return ResourceManager.GetString("TeamDetails_TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name:.
        /// </summary>
        public static string TeamName_Text {
            get {
                return ResourceManager.GetString("TeamName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TeamsHeader_AppPanel {
            get {
                return ResourceManager.GetString("TeamsHeader_AppPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string UserInfo_Title {
            get {
                return ResourceManager.GetString("UserInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users in teams:.
        /// </summary>
        public static string UsersInTeams_Text {
            get {
                return ResourceManager.GetString("UsersInTeams_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s teams:.
        /// </summary>
        public static string UsersTeams_Text {
            get {
                return ResourceManager.GetString("UsersTeams_Text", resourceCulture);
            }
        }
    }
}
